system:
  name: Timeleap
  log: info
  PrintVersion: true
network:
  broker:
    uri: ws://broker:9123
    publicKey: ${BROKER_PUBLIC_KEY}
    timeout: 30s
rpc:
  cpus: 1
  gpus: 0
  ram: 1024
plugins:
  - type: websocket
    name: swiss.timeleap.watermarker
    endpoint: ws://swiss.timeleap.watermarker
    publicKey: ${PLUGIN_PUBLIC_KEY}
    functions:
      - name: addWatermarkToImage
        fee:
          amount: 1
          currency: USD
